name: ${name}
version: ${version}
main: ${group}.TopsPlugin
api-version: 1.21
description: Top players ranking system
softdepend: [AuraSkills, TimeReward, TrackPlayer, CoinsEngine]
load: POSTWORLD
author: FlyAwayMaking
website: https://github.com/flyawaymaking

commands:
  tops:
    description: Open tops GUI or manage tops
    usage: /<command> [reload|rewards]

permissions:
  topssystem.reload:
    description: Allows to reload tops configuration
    default: op
  topssystem.rewards:
    description: Allows to force distribute rewards
    default: op
  topssystem.exclude:
    description: Exclude from leaderboard
    default: op
